---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Dotfiles for the Kash Lab:
    - On GitHub:
        - abbr: GH
          href: https://github.com/MonstrousOgre/HomeLabConfig
