---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Public Services:
    - Bookmarks:
        icon: linkding.png
        href: https://bookmarks.kashlab.net/
        description: Bookmark manager & reference saver
        container: linkding
        target: _blank

    - Read-it-later:
        icon: readeck.png
        href: https://read.kashlab.net/
        description: Article archive & OPDS feed provider
        container: readeck
        target: _blank

    - Library:
        icon: sh-bookorbit.png
        href: https://library.kashlab.net/
        description: Digital library catalog
        container: bookorbit
        target: _blank

    - Task Manager:
        icon: vikunja.png
        href: https://tasks.kashlab.net/
        description: Task management, time-slots & scheduling
        container: vikunja
        target: _blank

- Private Services:
    - Notes:
        icon: sh-trilium.png
        href: https://notes.kashlab.net/
        description: Knowledge base & note workspace
        container: trilium
        target: _blank
        siteMonitor: http://trilium:8080

    - Git:
        icon: forgejo.png
        href: https://git.kashlab.net/
        description: Private self-hosted Git forge
        container: forgejo
        target: _blank
        siteMonitor: http://forgejo:3000

    - Container Management:
        icon: portainer.png
        href: https://services.kashlab.net/
        description: Docker container management for the Kash Lab
        container: portainer
        target: _blank
        siteMonitor: http://portainer:9000
