---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Public Services:
    - Bookmarks:
        href: https://bookmarks.kashlab.net/
        description: Bookmark manager for the Kash Lab

    - Read-it-later:
        href: https://read.kashlab.net/
        description: Allows you to save articles and read them later

    - Library:
        href: https://library.kashlab.net/
        description: Digital library for the Kash Lab

- Private Services:
    - Git:
        href: https://git.kashlab.net:8443/
        description: Git forge for the Kash Lab
